name: academyhq.io
#theme: jekyll-theme-cayman
remote_theme: chrisrhymes/bulma-clean-theme
markdwon: kramdown
title: AcademyHQ
description: Quick courses, guides and tutorials for developers
google_analytics: UA-39757952-3
kramdown:
  highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false

